analyzer:
  skip_excluded: true
excludes:
  scopes:
    # Exclude all test dependencies
    - pattern: ".*test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Exclude unit test dependencies."
    - pattern: "androidTest.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Exclude Android instrumented test dependencies."
    - pattern: ".*Test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
    # Exclude generic 'build' configurations (like annotation processors)
    - pattern: "kapt.*"
      reason: "BUILD_TOOL_OF"
      comment: "Annotation processors are not distributed."
    - pattern: "ksp.*"
      reason: "BUILD_TOOL_OF"
      comment: "Annotation processors are not distributed."
    # Exclude 'dev' configurations
    - pattern: "devDebug.*"
      reason: "BUILD_TOOL_OF"
      comment: "dev builds are not distributed."
    - pattern: "devRelease.*"
      reason: "BUILD_TOOL_OF"
      comment: "dev builds are not distributed."
    # Exclude 'build' configurations
    - pattern: "kotlin.*"
      reason: "BUILD_TOOL_OF"
      comment: "kotlin scopes"
    - pattern: "kover.*"
      reason: "BUILD_TOOL_OF"
      comment: "kotlin quality reporting"
    - pattern: ".*javaPreCompile.*"
      reason: "BUILD_TOOL_OF"
      comment: "build scope"
    - pattern: "coreLibraryDesugaring"
      reason: "BUILD_TOOL_OF"
      comment: "desugar scope"
    - pattern: ".*CompileClasspath"
      reason: "BUILD_TOOL_OF"
      comment: "Compile scope"
    - pattern: "swiftExportClasspathResolvable"
      reason: "BUILD_TOOL_OF"
      comment: "not needed scope"
    - pattern: ".*Benchmark.*"
      reason: "BUILD_TOOL_OF"
      comment: "not needed scope"
    - pattern: ".*NonMinified.*"
      reason: "BUILD_TOOL_OF"
      comment: "not needed scope"
    - pattern: ".*Baseline.*"
      reason: "BUILD_TOOL_OF"
      comment: "not needed scope"
  paths:
    # remove test gradle modules
    - pattern: "test-feature/**"
      reason: "TEST_TOOL_OF"
      comment: "This is module for testing."
    - pattern: "test-logic/**"
      reason: "TEST_TOOL_OF"
      comment: "This is module for testing."
    # build logic module
    - pattern: "build-logic/**"
      reason: "BUILD_TOOL_OF"
      comment: "convention build plugins."
    - pattern: "baseline-profile/**"
      reason: "TEST_TOOL_OF"
      comment: "This is module for creating the baseline."
    # Recursively (**) exclude all Ruby definition files
    - pattern: "**/Gemfile"
      reason: "OTHER"
      comment: "Disable Bundler analysis."
    - pattern: "**/Gemfile.lock"
      reason: "OTHER"
      comment: "Disable Bundler analysis."
