blank_issues_enabled: false
contact_links:
  - name: Not a bug? Head to the discussion forum
    url: https://github.com/eu-digital-identity-wallet/av-doc-technical-specification/discussions
    about: Please ask and answer general questions here.
